backend:
  name: github
  repo: himanchal08/cms-dashboard
  branch: main
  base_url: https://vtn-cms-dashboard.netlify.app  # ✅ Required for GitHub OAuth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
