backend:
  name: github
  repo: himanchal08/cms-dashboard
  branch: main
  site_domain: https://68480c8c70e65a908d94bda7--vtn-cms-dashboard.netlify.app/

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
